services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sga
      POSTGRES_PASSWORD: sga@senhaForte!
      POSTGRES_DB: db_sga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=sga@senhaForte!
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: